application:
  audit:
    sink:
      connectionRef: "{{ myConnection }}"


  accessPolicies:
    apply: true
    location: EU


  #connectionRef: {{ connection_ref }}
  spark:
    datasource:
      bigquery:
        allowFieldAddition: "true"
        allowFieldRelaxation: "true"

  connections:
    bigquery:
      type: "bigquery"
      options:
        gcsBucket: "starlake-app"
        authType: "APPLICATION_DEFAULT"
        authScopes: "https://www.googleapis.com/auth/cloud-platform" # comma separated list of scopes
        #authType: SERVICE_ACCOUNT_JSON_KEYFILE
        #jsonKeyfile: "/Users/hayssams/.gcloud/keys/starlake-hayssams.json"

        #authType: "ACCESS_TOKEN"
        #gcpAccessToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sparkLocal:
      type: "fs"


  # loader: "spark" # "spark" or "native"
  connectionRef: {{ myConnection }}
